name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ["18.x", "20.x"]
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Deno
        uses: denoland/setup-deno@v1

      - name: Install dependencies
        run: npm install --no-scripts

      - name: Lint
        run: npm run lint

      - name: Format check
        run: npm run format:check

      - name: Build
        run: npm run build

      - name: Test
        run: |
          npm run test:ci
          npm run test:ci:legacy

      - name: Upload coverage reports to Codecov
        # Only upload coverage reports once
        if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
        uses: codecov/codecov-action@v3
        with:
          directory: ./.tap/report

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [test]
    if: |
      github.repository == 'nifty-lil-tricks/monitoring' &&
      github.ref == 'refs/heads/main'

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set up Node.js
        uses: actions/setup-node@v3

      - name: Create app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.NIFTY_LIL_TRICKS_BOT_APP_ID }}
          private-key: ${{ secrets.NIFTY_LIL_TRICKS_BOT_PRIVATE_KEY }}

      - name: Release if version change
        shell: bash
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./_tools/release.ts

  automerge:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
